### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Robigus92** [justdave/nwsweatheralertswidget#32]
After a double rotation of the MainActivity there are in heap memory 2 instances more of:

class net.justdave.nwsweatheralertswidget.MainActivity$4 @ 0x12c7f500
class net.justdave.nwsweatheralertswidget.MainActivity @ 0x12c8c800

It should not be like this because the rotations return to the same GUI state and the memory should stay in the same state as well. It could be a symptom of a bad management of the onCreate-onDestroy lifecycle.

**Comment by justdave** [comment]
This is likely the case, I notice all the state is lost when it rotates as well (if you had a lot in the list and had scrolled down for example).

**Comment by justdave** [comment]
Going to close this now as the branch this bug occurred in is no longer supported. If you run into this again after version 2.0 is released, please file a new issue. I can no longer update the 1.x branch on Google Play due to API violations that require a decent amount of the code to be rewritten from scratch to fix.
