### ISSUE TITLE
I had a crash when I used it.

### ISSUE THREAD

**Issue by YYYSSSHHH** [justdave/nwsweatheralertswidget#40]
**Environment Info：**
AndroidOS Version = 6.0.1
NWSWeather：android:versionCode="10" android:versionName="1.1.3"
**Crash Info:**
crashActivity=net.justdave.nwsweatheralertswidget.AlertDetailActivity
:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
	at net.justdave.nwsweatheralertswidget.AlertDetailActivity$1.run(AlertDetailActivity.java:62)
	at java.lang.Thread.run(Thread.java:818)

**Finally：**
The cause of the program crash may be that the network response data is not handled properly in the code, such as null.
If you have confirmed or fixed this problem, please give me a reply, thank you!

**Comment by justdave** [comment]
Was it showing "waiting for feed download" on the entry you tapped on? I know I had a known issue with it trying to actually react to that one when it was supposed to just be informational. Otherwise it's possible the NWS didn't provide an event details URL in the alert (which I'm probably stupidly assuming is present instead of checking it)

**Comment by YYYSSSHHH** [comment]
When I test APK automatically, most alerts are normal. 
 In a few cases, when I click a certain one, this alert will cause the app to crash.
soI think it is a more likely scenario that ：" it's possible the NWS didn't provide an event details URL in the alert ".

**Comment by justdave** [comment]
Going to close this now as the branch this bug occurred in is no longer supported.  If you run into this again after version 2.0 is released, please file a new issue.
